dist: xenial
sudo: required

os:
  - linux

python:
  - "2.7"

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

language: go
go: 1.10.x
install: true

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel

install:
  - wget -q https://github.com/bazelbuild/buildtools/releases/download/0.22.0/buildifier
  - chmod +x ./buildifier

script:
  # Test things by executing the various build configurations under testing/
  - buildifier --lint=warn --warnings=attr-cfg,attr-license,attr-non-empty,attr-output-default,attr-single-file,confusing-name,constant-glob,ctx-actions,ctx-args,depset-iteration,depset-union,dict-concatenation,duplicated-name,filetype,function-docstring,git-repository,http-archive,integer-division,load,load-on-top,module-docstring,name-conventions,native-build,native-package,no-effect,out-of-order-load,output-group,package-name,package-on-top,redefined-variable,repository-name,same-origin-load,string-iteration,unreachable,unsorted-dict-items,unused-variable container/load.bzl container/pull.bzl
  - ./testing/e2e.sh
